/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as MainArticlesIndexRouteImport } from './routes/_main/articles/index'
import { Route as MainMeProfileRouteImport } from './routes/_main/me/profile'
import { Route as MainMePathnameRouteImport } from './routes/_main/me/$pathname'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const MainArticlesIndexRoute = MainArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => MainRoute,
} as any)
const MainMeProfileRoute = MainMeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainMePathnameRoute = MainMePathnameRouteImport.update({
  id: '/me/$pathname',
  path: '/me/$pathname',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/me/$pathname': typeof MainMePathnameRoute
  '/me/profile': typeof MainMeProfileRoute
  '/articles/': typeof MainArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/me/$pathname': typeof MainMePathnameRoute
  '/me/profile': typeof MainMeProfileRoute
  '/articles': typeof MainArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/_main/me/$pathname': typeof MainMePathnameRoute
  '/_main/me/profile': typeof MainMeProfileRoute
  '/_main/articles/': typeof MainArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/$pathname'
    | '/me/$pathname'
    | '/me/profile'
    | '/articles/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/$pathname' | '/me/$pathname' | '/me/profile' | '/articles'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/auth/$pathname'
    | '/_main/me/$pathname'
    | '/_main/me/profile'
    | '/_main/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  AuthPathnameRoute: typeof AuthPathnameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/articles/': {
      id: '/_main/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof MainArticlesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/me/profile': {
      id: '/_main/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MainMeProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/me/$pathname': {
      id: '/_main/me/$pathname'
      path: '/me/$pathname'
      fullPath: '/me/$pathname'
      preLoaderRoute: typeof MainMePathnameRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainMePathnameRoute: typeof MainMePathnameRoute
  MainMeProfileRoute: typeof MainMeProfileRoute
  MainArticlesIndexRoute: typeof MainArticlesIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainMePathnameRoute: MainMePathnameRoute,
  MainMeProfileRoute: MainMeProfileRoute,
  MainArticlesIndexRoute: MainArticlesIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  AuthPathnameRoute: AuthPathnameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
